# Contexts

This notebook allows us to examine the contexts in which words occur in sentences throughout the two subcorpora. Contexts vary according to the method used:

- Using the already-generated SVOs, we can quickly glimpse the related subjects, verbs, and objects for a particular word, though it has to be appear somewhere as an S, V, or O.
- Using NLTK's `concordance` functionality we can explore all a word's contexts in the conventional KWiC format -- there is also code here for those interested in lemmatizing words before generating an NLTK `text`.

In [25]:
# IMPORTS
import pandas as pd

# LOAD DATAFRAMES
# the `lem` suffix indicates the verbs have been lemmatized
df_load = pd.read_csv("../output/contexts-upto2svos.csv", low_memory=False)

In [26]:
# Get a list of all the columns
columns = df_load.columns.tolist()
print(columns)

['Unnamed: 0', 'Talk_ID', 'public_url', 'headline', 'description', 'event', 'duration', 'published', 'tags', 'views', 'text', 'speaker_1', 'speaker_2', 'speaker_3', 'speaker_4', 'talk_gender', 'sentence', 'sentence_id', 's1', 'v1', 'o1', 's2', 'v2', 'o2']

In [27]:
# Drop columns for the sake of visual clarity
drop = ['Talk_ID', 'public_url', 'duration', 'published', 'text',
        'description', 'tags', 'speaker_2', 'speaker_3', 'speaker_4']
df = df_load.drop(columns=drop)

In [28]:
df.query('(s1=="he" or s2=="he") & (v1=="kill" or v2=="kill")')

,Unnamed: 0,headline,event,views,speaker_1,talk_gender,sentence,sentence_id,s1,v1,o1,s2,v2,o2
25953,25953,The transformative power of classical music,TED2008,9968703,Benjamin Zander,male,"That's in order to delay — until Act Five, he ...",286-130,he,kill,him,NaN,NaN,NaN
59422,59422,How I became 100 artists,TED2011,1525148,Shea Hembrey,male,"But when I was little, I remember, he would ki...",1169-10,he,kill,flies,NaN,NaN,NaN
59424,59424,How I became 100 artists,TED2011,1525148,Shea Hembrey,male,And what was amazing to me — well it was prett...,1169-12,he,kill,fly,NaN,NaN,NaN
67718,67718,My invention that made peace with lions,TED2013,2174131,Richard Turere,male,(Laughter) So he jumps in and kills the animals.,1699-23,he,jump,animals,he,kill,animals
68555,68555,In search of the man who broke my neck,TED2013,1405153,Joshua Prager,male,"I told him only that he had killed one man, no...",1715-158,I,tell,him,he,kill,man
101472,101472,The illustrated woman,TED2007,702690,Maira Kalman,female,"And so, this is a chart of, you know, just a s...",182-135,he,kill,that,NaN,NaN,NaN
102679,102679,My wish: The Charter for Compassion,TED2008,1433701,Karen Armstrong,female,"He kills Hector, he mutilates his body and the...",234-115,He,kill,Hector,he,mutilate,body
104031,104031,"Once upon a time, my mother ...",TED2005,739635,Carmen Agra Deedy,female,"And so we left my father fast asleep, because ...",347-122,we,leave,father,he,kill,me

In [61]:
pp= "he"
vb= "kill"
filtered = df.query(
    '(s1==@pp or s2==@pp) & (v1==@vb or v2==@vb) & talk_gender=="female"'
    )['sentence']
for i in filtered:
    print(f"{i}\n")

And so, this is a chart of, you know, just a small chart, because the chart would go on forever of all the people that he killed.

He kills Hector, he mutilates his body and then he refuses to give the body back for burial to the family, which means that, in Greek ethos, Hector's soul will wander eternally, lost.

And so we left my father fast asleep, because I knew he'd kill me if I let her go by herself, and we get in the car.

In [65]:
def contexts (subject, verb):
    pp= subject
    vb= verb
    women = df.query(
        '(s1==@pp or s2==@pp) & (v1==@vb or v2==@vb) & talk_gender=="female"'
        )['sentence']
    men = df.query(
        '(s1==@pp or s2==@pp) & (v1==@vb or v2==@vb) & talk_gender=="male"'
        )['sentence']
    for i in women:
        print(f"F: {i}\n")
    for i in men:
        print(f"M: {i}\n")

In [66]:
contexts("he", "kill")

F: And so, this is a chart of, you know, just a small chart, because the chart would go on forever of all the people that he killed.

F: He kills Hector, he mutilates his body and then he refuses to give the body back for burial to the family, which means that, in Greek ethos, Hector's soul will wander eternally, lost.

F: And so we left my father fast asleep, because I knew he'd kill me if I let her go by herself, and we get in the car.

M: That's in order to delay — until Act Five, he can kill him.

M: But when I was little, I remember, he would kill flies in our house with my BB gun.

M: And what was amazing to me — well it was pretty kickass; he was killing a fly in the house with a gun — but what was so amazing to me was that he knew just enough how to pump it.

M: (Laughter) So he jumps in and kills the animals.

M: I told him only that he had killed one man, not two.